### ISSUE TITLE
Fix horizontal checkWin

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL23/solver-consnect-f0ur#20]
You can either pad things out to the maximum size of any column with Maybes (ewwww), or write something that checks horizontals without transpose. I would suggest writing something that creates/checks chains of 4. You will need a sliding window of 4 columns at a time. Reverse the columns (to avoid having to pad), check them in lockstep. 

To get diagonals, drop elements from the 2nd, 3rd, and 4th list (or 1st, 2nd, and 3rd) to make it horizontal again. Where you do this after the reverse can be tricky.

**Comment by Jino-T** [comment]
When fixed we need to also test unsafeGameWin
